[package]
name = "embedded-static-ref-cell"
version = "1.0.0"
edition = "2021"

[dependencies]
critical-section = "1.1.1"

[dev-dependencies]
critical-section = {version = "1.1.1", features = ["std"]}
