name: CI

# This workflow run tests and build for each push

on:
  push:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly          

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version          

      - name: Lint
        run: |
          cd embedded-static-ref-cell
          cargo fmt -- --check
          cargo clippy -- -D warnings          

      - name: Test
        run: |
          cd embedded-static-ref-cell
          cargo check
          cargo test --all          

      - name: Build
        run: |
          cd embedded-static-ref-cell
          cargo build --release
          
      - name: Build Docs
        run: |
          cd embedded-static-ref-cell
          cargo doc
